# Generated by Django 4.2.30 on 2026-05-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_providercredential_last_used_token_rotation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="providercredential",
            name="provider",
            field=models.CharField(
                choices=[
                    ("ollama", "Ollama"),
                    ("openai", "OpenAI"),
                    ("gemini", "Gemini"),
                    ("openrouter", "OpenRouter"),
                ],
                max_length=32,
            ),
        ),
    ]
